- name: User Setup
  hosts: all
  become: true
  vars:
    - component: user
    - schema_type: mongodb
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{component}}"

    - name: Import task from nodejs.yml.
      ansible.builtin.import_tasks: nodejs.yml